/*
 * Student is Shareef Aldahhan
 * Student ID is 991598634
 */
package project.uno;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author share
 */
public class AddPlayerNames extends javax.swing.JFrame {
    
    public ArrayList<String> playerIDs;
    /**
     * Creates new form addPlayerNames
     */
    public AddPlayerNames() {
        initComponents();
        playerIDs = new ArrayList<>();
    }
    public String[] getPids(){
        String[] pids = playerIDs.toArray(new String[playerIDs.size()]);
        return pids;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SAVE = new javax.swing.JButton();
        Done = new javax.swing.JButton();
        NameE = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PassE = new javax.swing.JTextField();
        playerNumOne = new javax.swing.JTextField();
        playerNumThree = new javax.swing.JTextField();
        playerNumTwo = new javax.swing.JTextField();
        playerNumFour = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        Done.setText("DONE");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UNO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Name of Player:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Password:");

        playerNumOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNumOneActionPerformed(evt);
            }
        });

        playerNumThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNumThreeActionPerformed(evt);
            }
        });

        playerNumTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNumTwoActionPerformed(evt);
            }
        });

        playerNumFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNumFourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(NameE)
                                .addComponent(PassE, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                            .addComponent(Done, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerNumOne, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerNumThree, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(playerNumFour, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(playerNumTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(46, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(PassE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerNumOne, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerNumTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerNumThree, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerNumFour, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Done, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerNumOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNumOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerNumOneActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
         boolean validPassword=false;
         
         int specialCharCount=0;
            for(int i=0;i<PassE.getText().length(); i++)
            {
                if(!(Character.isLetterOrDigit(PassE.getText().charAt(i))))
                {
                    //now we know there is at least one special character
                    specialCharCount++;
                    
                }
            }
        if(PassE.getText().isEmpty()){
            JLabel message = new JLabel("Please enter in a Password ");
            message.setFont(new Font("Arial",Font.BOLD,22));
            JOptionPane.showMessageDialog(null,message);
            } else if(specialCharCount<1  && PassE.getText().length()<7)
        {
            JLabel message = new JLabel("Password must be 8 character or more ");
            message.setFont(new Font("Arial",Font.BOLD,22));
            JOptionPane.showMessageDialog(null,message);
            //iterate over each character to see if it is a special character
        }else {
        String Pass = PassE.getText();
               
        if(NameE.getText().isEmpty()){
            JLabel message = new JLabel("Please enter in a name ");
            message.setFont(new Font("Arial",Font.BOLD,28));
            JOptionPane.showMessageDialog(null,message);
        }else {
            String Name = NameE.getText().trim();
            playerIDs.add (Name);
            
            if(playerIDs.size() == 1){
                playerNumOne.setText(playerIDs.get(0));
            }
            if(playerIDs.size() == 2){
                playerNumOne.setText(playerIDs.get(0));
                playerNumTwo.setText(playerIDs.get(1));
            }
            if(playerIDs.size() == 3){
                playerNumOne.setText(playerIDs.get(0));
                playerNumTwo.setText(playerIDs.get(1));
                playerNumThree.setText(playerIDs.get(2));
            }
            if(playerIDs.size() == 4){
                playerNumOne.setText(playerIDs.get(0));
                playerNumTwo.setText(playerIDs.get(1));
                playerNumThree.setText(playerIDs.get(2));
                playerNumFour.setText(playerIDs.get(3));
            }
            if(playerIDs.size() > 0 && playerIDs.size() <5  && validPassword == true){
             JLabel message = new JLabel("Please enter in a name ");
            message.setFont(new Font("Arial",Font.BOLD,28));
            JOptionPane.showMessageDialog(null,message);
            NameE.setText("");
            PassE.setText("");
         }
       if(playerIDs.size() == 5){
           playerIDs.remove(Name);
           JLabel message = new JLabel("max players 4 ");
           message.setFont(new Font("Arial",Font.BOLD,28));
           JOptionPane.showMessageDialog(null,message);
           NameE.setText("");
        }
    }//GEN-LAST:event_SAVEActionPerformed
    }
    }
    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        // TODO add your handling code here:
        if (playerIDs.size() ==1 || playerIDs.size() ==0 ){
           JLabel message = new JLabel("There must be at least 2 Players ");
           message.setFont(new Font("Arial",Font.BOLD,28));
           JOptionPane.showMessageDialog(null,message);
           NameE.setText("");
        }else {
            this.dispose();
            new GameStage(playerIDs).setVisible(true);
        }
    }//GEN-LAST:event_DoneActionPerformed

    private void playerNumThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNumThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerNumThreeActionPerformed

    private void playerNumTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNumTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerNumTwoActionPerformed

    private void playerNumFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNumFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerNumFourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPlayerNames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Done;
    private javax.swing.JTextField NameE;
    private javax.swing.JTextField PassE;
    private javax.swing.JButton SAVE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField playerNumFour;
    private javax.swing.JTextField playerNumOne;
    private javax.swing.JTextField playerNumThree;
    private javax.swing.JTextField playerNumTwo;
    // End of variables declaration//GEN-END:variables
}
